{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hivebox.fullname" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec: 
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules: 
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - pathType: {{ .pathType }}
            path:  {{ .path }}
            backend:
              service:
                name: {{ include "hivebox.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
      {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}