apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivebox.fullname" . }}
  labels:
    app: {{ include "hivebox.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hivebox.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP 
      name: http